#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnl
Version  : 3.2.25
Release  : 14
URL      : http://www.infradead.org/~tgr/libnl/files/libnl-3.2.25.tar.gz
Source0  : http://www.infradead.org/~tgr/libnl/files/libnl-3.2.25.tar.gz
Summary  : Generic Netlink Library
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1
Requires: libnl-bin
Requires: libnl-lib
Requires: libnl-data
Requires: libnl-doc
BuildRequires : bison
BuildRequires : flex
BuildRequires : pkgconfig(check)

%description
***************************************************************************
NOTE: The python wrapper is experimental and may or may not work.

%package bin
Summary: bin components for the libnl package.
Group: Binaries
Requires: libnl-data

%description bin
bin components for the libnl package.


%package data
Summary: data components for the libnl package.
Group: Data

%description data
data components for the libnl package.


%package dev
Summary: dev components for the libnl package.
Group: Development
Requires: libnl-lib
Requires: libnl-bin
Requires: libnl-data

%description dev
dev components for the libnl package.


%package doc
Summary: doc components for the libnl package.
Group: Documentation

%description doc
doc components for the libnl package.


%package lib
Summary: lib components for the libnl package.
Group: Libraries
Requires: libnl-data

%description lib
lib components for the libnl package.


%prep
%setup -q -n libnl-3.2.25

%build
%configure --disable-static --sysconfdir=/usr/share/defaults
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/libnl/cli/cls/basic.so
/usr/lib64/libnl/cli/cls/cgroup.so
/usr/lib64/libnl/cli/qdisc/bfifo.so
/usr/lib64/libnl/cli/qdisc/blackhole.so
/usr/lib64/libnl/cli/qdisc/fq_codel.so
/usr/lib64/libnl/cli/qdisc/htb.so
/usr/lib64/libnl/cli/qdisc/ingress.so
/usr/lib64/libnl/cli/qdisc/pfifo.so
/usr/lib64/libnl/cli/qdisc/plug.so

%files bin
%defattr(-,root,root,-)
/usr/bin/genl-ctrl-list
/usr/bin/nl-class-add
/usr/bin/nl-class-delete
/usr/bin/nl-class-list
/usr/bin/nl-classid-lookup
/usr/bin/nl-cls-add
/usr/bin/nl-cls-delete
/usr/bin/nl-cls-list
/usr/bin/nl-link-list
/usr/bin/nl-pktloc-lookup
/usr/bin/nl-qdisc-add
/usr/bin/nl-qdisc-delete
/usr/bin/nl-qdisc-list

%files data
%defattr(-,root,root,-)
/usr/share/defaults/libnl/classid
/usr/share/defaults/libnl/pktloc

%files dev
%defattr(-,root,root,-)
/usr/include/libnl3/netlink/addr.h
/usr/include/libnl3/netlink/attr.h
/usr/include/libnl3/netlink/cache-api.h
/usr/include/libnl3/netlink/cache.h
/usr/include/libnl3/netlink/cli/addr.h
/usr/include/libnl3/netlink/cli/class.h
/usr/include/libnl3/netlink/cli/cls.h
/usr/include/libnl3/netlink/cli/ct.h
/usr/include/libnl3/netlink/cli/exp.h
/usr/include/libnl3/netlink/cli/link.h
/usr/include/libnl3/netlink/cli/neigh.h
/usr/include/libnl3/netlink/cli/qdisc.h
/usr/include/libnl3/netlink/cli/route.h
/usr/include/libnl3/netlink/cli/rule.h
/usr/include/libnl3/netlink/cli/tc.h
/usr/include/libnl3/netlink/cli/utils.h
/usr/include/libnl3/netlink/data.h
/usr/include/libnl3/netlink/errno.h
/usr/include/libnl3/netlink/fib_lookup/lookup.h
/usr/include/libnl3/netlink/fib_lookup/request.h
/usr/include/libnl3/netlink/genl/ctrl.h
/usr/include/libnl3/netlink/genl/family.h
/usr/include/libnl3/netlink/genl/genl.h
/usr/include/libnl3/netlink/genl/mngt.h
/usr/include/libnl3/netlink/handlers.h
/usr/include/libnl3/netlink/hash.h
/usr/include/libnl3/netlink/hashtable.h
/usr/include/libnl3/netlink/idiag/idiagnl.h
/usr/include/libnl3/netlink/idiag/meminfo.h
/usr/include/libnl3/netlink/idiag/msg.h
/usr/include/libnl3/netlink/idiag/req.h
/usr/include/libnl3/netlink/idiag/vegasinfo.h
/usr/include/libnl3/netlink/list.h
/usr/include/libnl3/netlink/msg.h
/usr/include/libnl3/netlink/netfilter/ct.h
/usr/include/libnl3/netlink/netfilter/exp.h
/usr/include/libnl3/netlink/netfilter/log.h
/usr/include/libnl3/netlink/netfilter/log_msg.h
/usr/include/libnl3/netlink/netfilter/netfilter.h
/usr/include/libnl3/netlink/netfilter/nfnl.h
/usr/include/libnl3/netlink/netfilter/queue.h
/usr/include/libnl3/netlink/netfilter/queue_msg.h
/usr/include/libnl3/netlink/netlink-compat.h
/usr/include/libnl3/netlink/netlink-kernel.h
/usr/include/libnl3/netlink/netlink.h
/usr/include/libnl3/netlink/object-api.h
/usr/include/libnl3/netlink/object.h
/usr/include/libnl3/netlink/route/act/mirred.h
/usr/include/libnl3/netlink/route/action.h
/usr/include/libnl3/netlink/route/addr.h
/usr/include/libnl3/netlink/route/class.h
/usr/include/libnl3/netlink/route/classifier.h
/usr/include/libnl3/netlink/route/cls/basic.h
/usr/include/libnl3/netlink/route/cls/cgroup.h
/usr/include/libnl3/netlink/route/cls/ematch.h
/usr/include/libnl3/netlink/route/cls/ematch/cmp.h
/usr/include/libnl3/netlink/route/cls/ematch/meta.h
/usr/include/libnl3/netlink/route/cls/ematch/nbyte.h
/usr/include/libnl3/netlink/route/cls/ematch/text.h
/usr/include/libnl3/netlink/route/cls/fw.h
/usr/include/libnl3/netlink/route/cls/police.h
/usr/include/libnl3/netlink/route/cls/u32.h
/usr/include/libnl3/netlink/route/link.h
/usr/include/libnl3/netlink/route/link/api.h
/usr/include/libnl3/netlink/route/link/bonding.h
/usr/include/libnl3/netlink/route/link/bridge.h
/usr/include/libnl3/netlink/route/link/can.h
/usr/include/libnl3/netlink/route/link/inet.h
/usr/include/libnl3/netlink/route/link/info-api.h
/usr/include/libnl3/netlink/route/link/ip6tnl.h
/usr/include/libnl3/netlink/route/link/ipgre.h
/usr/include/libnl3/netlink/route/link/ipip.h
/usr/include/libnl3/netlink/route/link/ipvti.h
/usr/include/libnl3/netlink/route/link/macvlan.h
/usr/include/libnl3/netlink/route/link/sit.h
/usr/include/libnl3/netlink/route/link/veth.h
/usr/include/libnl3/netlink/route/link/vlan.h
/usr/include/libnl3/netlink/route/link/vxlan.h
/usr/include/libnl3/netlink/route/neighbour.h
/usr/include/libnl3/netlink/route/neightbl.h
/usr/include/libnl3/netlink/route/nexthop.h
/usr/include/libnl3/netlink/route/pktloc.h
/usr/include/libnl3/netlink/route/qdisc.h
/usr/include/libnl3/netlink/route/qdisc/cbq.h
/usr/include/libnl3/netlink/route/qdisc/dsmark.h
/usr/include/libnl3/netlink/route/qdisc/fifo.h
/usr/include/libnl3/netlink/route/qdisc/fq_codel.h
/usr/include/libnl3/netlink/route/qdisc/htb.h
/usr/include/libnl3/netlink/route/qdisc/netem.h
/usr/include/libnl3/netlink/route/qdisc/plug.h
/usr/include/libnl3/netlink/route/qdisc/prio.h
/usr/include/libnl3/netlink/route/qdisc/red.h
/usr/include/libnl3/netlink/route/qdisc/sfq.h
/usr/include/libnl3/netlink/route/qdisc/tbf.h
/usr/include/libnl3/netlink/route/route.h
/usr/include/libnl3/netlink/route/rtnl.h
/usr/include/libnl3/netlink/route/rule.h
/usr/include/libnl3/netlink/route/tc-api.h
/usr/include/libnl3/netlink/route/tc.h
/usr/include/libnl3/netlink/socket.h
/usr/include/libnl3/netlink/types.h
/usr/include/libnl3/netlink/utils.h
/usr/include/libnl3/netlink/version.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
